//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice3_sokolova_22._102
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelAgentEntities2 : DbContext
    {
        public TravelAgentEntities2()
            : base("name=TravelAgentEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agents> Agents { get; set; }
        public virtual DbSet<Authorizations> Authorizations { get; set; }
        public virtual DbSet<Beaches> Beaches { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Contacts> Contacts { get; set; }
        public virtual DbSet<Contracts> Contracts { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<DeparturesDates> DeparturesDates { get; set; }
        public virtual DbSet<Directions> Directions { get; set; }
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<Excursions> Excursions { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<Hotels> Hotels { get; set; }
        public virtual DbSet<Intermediaries> Intermediaries { get; set; }
        public virtual DbSet<IntermediariesReports> IntermediariesReports { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TaxReports> TaxReports { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
        public virtual DbSet<Tours> Tours { get; set; }
        public virtual DbSet<TicketsCustomers> TicketsCustomers { get; set; }
    }
}
