//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice3_sokolova_22._102
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxReports
    {
        public long tax_report_id { get; set; }
        public int tax_report_number { get; set; }
        public long agent_id { get; set; }
    
        public virtual Agents Agents { get; set; }
    }
}
