//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice3_sokolova_22._102
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tickets()
        {
            this.TicketsCustomers = new HashSet<TicketsCustomers>();
        }
    
        public long ticket_id { get; set; }
        public System.DateTime departure_from { get; set; }
        public System.DateTime arrival_to { get; set; }
        public int nights_count { get; set; }
        public decimal cost { get; set; }
        public long tour_id { get; set; }
        public long customer_id { get; set; }
        public long agent_id { get; set; }
    
        public virtual Tours Tours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketsCustomers> TicketsCustomers { get; set; }
    }
}
