//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice3_sokolova_22._102
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Tours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tours()
        {
            this.Excursions = new HashSet<Excursions>();
            this.Tickets = new HashSet<Tickets>();
            this.Directions = new HashSet<Directions>();
            this.DeparturesDates = new HashSet<DeparturesDates>();
        }
    
        public long tour_id { get; set; }
        public long hotel_id { get; set; }
        public long departure_date_id { get; set; }
        public decimal cost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Excursions> Excursions { get; set; }
        public virtual Hotels Hotels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Directions> Directions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeparturesDates> DeparturesDates { get; set; }

        public string startDate {
            get
            {
                //return Helper.GetContext().DeparturesDates.
                if (this.DeparturesDates.Count == 0) 
                {
                    return string.Empty;
                }
                return this.DeparturesDates.FirstOrDefault().departure_start_date.ToString();
            }
        }

        public string endDate
        {
            get
            {
                //return Helper.GetContext().DeparturesDates.
                if (this.DeparturesDates.Count == 0)
                {
                    return string.Empty;
                }
                return this.DeparturesDates.FirstOrDefault().departure_end_date.ToString();
            }
        }
    }
}
